[versions]
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.0"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
argon2 = "1.82"
composeMultiplatform = "1.9.3"
exposed = "0.61.0"
h2 = "2.4.240"
javaJwt = "4.5.0"
junit = "4.13.2"
kotlin = "2.2.21"
ktor = "3.3.2"
koin = "4.1.1"
coil3 = "3.3.0"
ksp = "2.2.20-2.0.4"
sqlite = "2.6.2"
room = "2.8.4"
logback = "1.5.21"
composeNavigation = "2.9.1"
kotlinSerialization = "1.9.0"
compose-icons = "1.1.1"
kotlinxCoroutines = "1.10.2"
datastore = "1.2.0"
playServicesLocation = "21.3.0"
mokoPermissions = "0.18.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

compose-icons = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "compose-icons" }

compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation"}
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization"}
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines"}

play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
moko-permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "mokoPermissions" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin"}
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin"}
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin"}

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3"}
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3"}
coil-network-ktor2 = { module = "io.coil-kt.coil3:coil-network-ktor2", version.ref = "coil3"}
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3"}
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3"}

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room"}
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite"}

ktor-client-core = { module =" io.ktor:ktor-client-core", version.ref = "ktor"}
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor"}
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor"}
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor"}
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor"}
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor"}
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor"}

ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor"}
ktor-server-statusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor"}
ktor-server-callLogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor"}
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor"}
ktor-server-hostCommon = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor"}
ktor-server-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor"}
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor"}
ktor-server-authJwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor"}
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-testHost = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }

h2 = { module = "com.h2database:h2", version.ref = "h2" }

argon2 = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "argon2"}
java-jwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}

[bundles]
koin = [
    "koin-core",
    "koin-compose",
    "koin-compose-viewmodel"
]
coil = [
    "coil-compose",
    "coil-compose-core",
    "coil-network-ktor2",
    "coil-network-ktor3",
    "coil-mp"
]
ktor-client = [
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-client-auth",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json",
]
ktor-server = [
    "ktor-server-core",
    "ktor-server-netty",
    "ktor-server-hostCommon",
    "ktor-server-contentNegotiation",
    "ktor-server-auth",
    "ktor-server-authJwt",
    "ktor-server-cio",
    "ktor-server-cors",
    "ktor-server-statusPages",
    "ktor-server-callLogging",
    "ktor-server-testHost"
]
exposed = [
    "exposed-core",
    "exposed-dao",
    "exposed-jdbc",
    "exposed-java-time"
]
